### ISSUE TITLE
New factors cannot be added

### ISSUE THREAD

**Issue by behnamxa** [APSIMInitiative/ApsimX#3302]
While previous factors in my APSIM files (like those in the validation files) work fine, I cannot add new factors. When I try to type the name of an object that is already in the **Zone** (e.g. **[Sowing]**) to link to to the factor, after I save or click on another item in the tree, the name of the object that I had typed will be gone, **Unless I first Click on the Experiment Object**! It randomly happens.

![image](https://user-images.githubusercontent.com/39573622/48685479-42d2c880-ec02-11e8-9e01-cefcaa11a92a.png)

![image](https://user-images.githubusercontent.com/39573622/48685495-50884e00-ec02-11e8-962e-387eb1be3f89.png)

![image](https://user-images.githubusercontent.com/39573622/48685503-5a11b600-ec02-11e8-9f7f-f0a17c3edf67.png)

**Comment by hol430** [comment]
Have you done a pull recently? I fixed several similar bugs on Friday last week. It seems to be working ok for me now.

**Comment by behnamxa** [comment]
Yes, the branch is up-to-date. As I said, it only randomly happens. I tried different factors. Sometimes it happens and sometimes it doesn't. 
Here is an example. Try to link the first factor to [Fertilisation].
[APAD2018.zip](https://github.com/APSIMInitiative/ApsimX/files/2593748/APAD2018.zip)

**Comment by behnamxa** [comment]
BTW, there are a few more problems with the factors. For example, when I disable a number of simulations, like that for the cultivar **SERI** (which doesn't exist in the list of cultivars), it is still run and an exception is thrown. When I disable the **SERI** factor itself, no exception is thrown, but that simulation is still shown in the daily report (with all traits set at zero except zadoks stage). 

![3](https://user-images.githubusercontent.com/39573622/48686519-1a4dcd00-ec08-11e8-92ec-d89a7b333e81.png)
![1](https://user-images.githubusercontent.com/39573622/48686516-19b53680-ec08-11e8-84b2-96cb2c46de64.png)
![2](https://user-images.githubusercontent.com/39573622/48686518-1a4dcd00-ec08-11e8-87ad-fe32f29d8b35.png)

**Comment by hol430** [comment]
Yeah, enabling/disabling of individual simulations in the experiment view currently doesn't work very well (or at all, usually). @hol353 is currently refactoring the whole experiment/factor mess, so it should be working again once he finishes.
