### ISSUE TITLE
Expand 'edit apsimx file' functionality

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4905]
Need to be able to replace a model from an external file via the command line when using the /Edit command-line switch.

**Comment by frank0434** [comment]
might be relevant for this topic? 
https://github.com/hol430/ApsimOnR/issues/1#issue-579633917

**Comment by frank0434** [comment]
@hol430 

wondering if you could share a template for the `config_file.txt` 

I've just tried to use the `Models.exe` approach to produce `Apsimx` files. 
But got these errors:

**Comment by hol430** [comment]
Looks like the path is invalid. I'm guessing you copied this from the GUI so there's probably a bug there which I'll look into. The error message was also not very helpful - I will see if I can get a better error message when this happens.

In the short term, try getting rid of Base from the front of your path so it looks like `.Simulations.SimulationExp......`

**Comment by frank0434** [comment]
Yes. copied from the GUI. 
thanks for getting on this promptly.

**Comment by frank0434** [comment]
@hol430 

Trying to modify the path with the updated `/Edit` feature. 
Have a few issues with the output.  I think it may be caused by the type of the strings/DateTime
The config file I tried is formated as below: 
```
.Simulations.New Zealand.Iversen_12.Simulation3.Weather.FileName = "C:\Data\Master\01raw-data\ClimateAndObserved\lincoln.met"
.Simulations.New Zealand.Iversen_12.Simulation3.paddock.Soil.Physical.LucerneSoil.KL = "1,2,3,4,5,6,7,8,9,0"
.Simulations.Replacements.Lucerne.Leaf.Photosynthesis.FW.XYPairs.X = "2,3,4,5"
.Simulations.New Zealand.Iversen_12.Simulation3.clock.Start="1970-02-03T00:00:00"
.Simulations.New Zealand.Iversen_12.Simulation3.clock.end ="1980-02-03T00:00:00"
```

## Path string
for some reasons, there are escape slashes with double quotes sneaked into the modified `apsimx` file, which makes the path illegal 
```
 "$type": "Models.Weather, Models",
 "FileName": "\"C:\\Data\\Master\\01raw-data\\ClimateAndObserved\\lincoln.met\"",
 "ExcelWorkSheetName": null,
 "Name": "Weather",
 "Children": [],
 "IncludeInDocumentation": true,
 "Enabled": true,
 "ReadOnly": false
```

![image](https://user-images.githubusercontent.com/30789416/76578967-5c9eca00-652f-11ea-8024-d28dc40d7474.png)

Tried `single  quoate` in the config file. still passed to the output. 
```
"FileName": "'C:\\Data\\Master\\01raw-data\\ClimateAndObserved\\lincoln.met'",
```
## Datetime

Clock parameter failed to be modified as the error message suggested? 
```
 at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue, IFormatProvider format) in C:\Data\ApsimX20200311\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 379
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue) in C:\Data\ApsimX20200311\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 328
   at Models.Program.EditFile(String apsimxFileName, List`1 factors) in C:\Data\20200311ApsimX\Models\Main.cs:line 306
   at Models.Program.EditFile(String fileName, Boolean recurse) in C:\Data\20200311ApsimX\Models\Main.cs:line 203
   at Models.Program.Main(String[] args) in C:\Data\20200311ApsimX\Models\Main.cs:line 94
```

## double/float and xy pairs 

try to modify `kl` in the soil model and `FW` in the leaf organ 
Assume this is a similar message just suggest that the type of input is not right? 
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue, IFormatProvider format) in C:\Data\ApsimX20200311\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 379
   at APSIM.Shared.Utilities.ReflectionUtilities.<>c__DisplayClass17_0.<StringToObject>b__0(String s) in C:\Data\ApsimX20200311\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 362
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue, IFormatProvider format) in C:\Data\ApsimX20200311\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 362
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue) in C:\Data\ApsimX20200311\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 328
   at Models.Program.EditFile(String apsimxFileName, List`1 factors) in C:\Data\20200311ApsimX\Models\Main.cs:line 306
   at Models.Program.EditFile(String fileName, Boolean recurse) in C:\Data\20200311ApsimX\Models\Main.cs:line 203
   at Models.Program.Main(String[] args) in C:\Data\20200311ApsimX\Models\Main.cs:line 94
```

## Additional question 

wondering what is the best way to output the modified apsimx file without overwrite the original one? I have very limited knowledge of Powershell. so just tried something randomly as below 
```
..\20200311ApsimX\Bin\Models.exe .\01raw-data\ApsimxFiles\test.apsimx /Edit .\02scripts\test\config20200312.txt  > .\one.apsimx
..\20200311ApsimX\Bin\Models.exe .\01raw-data\ApsimxFiles\test.apsimx /Edit .\02scripts\test\config20200312.txt    | Set-Content  .\one.apsimx
```

both command just outputs the error message. I guess they are only recording the command feedback rather than the actual apsimx file  

thank you.

**Comment by hol430** [comment]
Hi Frank, can you try with no quotes around any of the values? e.g.

```
.Simulations.New Zealand.Iversen_12.Simulation3.Weather.FileName = C:\Data\Master\01raw-data\ClimateAndObserved\lincoln.met
.Simulations.New Zealand.Iversen_12.Simulation3.paddock.Soil.Physical.LucerneSoil.KL = 1,2,3,4,5,6,7,8,9,0
.Simulations.Replacements.Lucerne.Leaf.Photosynthesis.FW.XYPairs.X = 2,3,4,5
.Simulations.New Zealand.Iversen_12.Simulation3.clock.Start=1970-02-03T00:00:00
.Simulations.New Zealand.Iversen_12.Simulation3.clock.End =1980-02-03T00:00:00
```

As for not modifying the original file, I'd just copy the .apsimx file and edit the copy, e.g.

```
cp myfile.apsimx tempfile.apsimx
Models.exe tempfile.apsimx /Edit configfile.txt
```

**Comment by frank0434** [comment]
Hi Drew, it is working now. 

No quotes is the way to go. 

just discovered that a slightly misleading error message will be triggered if the weather file path has a number in it during editing. 
for example when configure file has **`01`** as part of the path
```
.Simulations.New Zealand.Iversen_12.Simulation3.Weather.FileName = C:\Data\Master\01raw-data\ClimateAndObserved\082039.met
```
```
System.Exception: Unable to find target model .Simulations.New Zealand.Iversen_12.Simulation3.Weather.FileName in file .\test.apsimx
```

the others are all good now. 

thank you a lot for the tips.

**Comment by hol430** [comment]
Interesting - I'll look into it. Would you be able to upload your .apsimx file and config file? I'll also see if I can mock up a proper example when I get the chance and will put it up on the website.

**Comment by frank0434** [comment]
sure can.  
I'm a bit confused now because the behaviour is not consistent. 
or the number is not the issue. it is the `dot` before the `met`.
removed the path component one by one. number as the start of a dir is fine. the error message popped up when the `*.met` present. 

here is the `config` and an `apsimx` file
[config20200312.txt](https://github.com/APSIMInitiative/ApsimX/files/4327647/config20200312.txt)
The `apsimx` file is not allowed to be in a comment so put it under the project repo [.Apsimx](https://github.com/frank0434/Master/blob/master/test.apsimx)
thanks 

also, found an interesting behaviour. 
the whole simulation is inserted into the original `apsimx` file if the config file only provides model node as below 
```
.Simulations.New Zealand.Iversen_12.Simulation3.Weather = C:\Data\Master\01raw-data\ClimateAndObserved\lincoln.met
```
snapshots as reference. 
wondering if this could be useful to replace the whole soil model node somehow? 
![image](https://user-images.githubusercontent.com/30789416/76587229-143fd600-6548-11ea-85fd-13eacd57bebc.png)

![image](https://user-images.githubusercontent.com/30789416/76587199-fc685200-6547-11ea-8a76-f932cbbdf017.png)

**Comment by hol430** [comment]
Hi Frank,

> just discovered that a slightly misleading error message will be triggered if the weather file path has a number in it during editing.
for example when configure file has 01 as part of the path

I'm unable to reproduce this one using your .apsimx and config files provided, even if I change to using a met file name with numbers in it.

> also, found an interesting behaviour.
the whole simulation is inserted into the original apsimx file if the config file only provides model node as below

This one is definitely a bug. Will get a fix up asap.

> wondering if this could be useful to replace the whole soil model node somehow as Neil mentioned in the catchup?

This should now be possible if you do something like this:

```
.Simulations.New Zealand.Iversen_12.Simulation3.Weather = C:\Data\Master\01raw-data\ClimateAndObserved\test.apsimx;.Simulations.MySimulation.Weather
```

That is, the left hand side should have the path to a model which you want to replace, the right hand side should have two values, separated by a semicolon. The first value should be the path to an .apsimx file, and the second part (after the semicolon) contains the path to a model inside this .apsimx file, which will be used to replace the model on the left hand side.

**Comment by hol430** [comment]
I'm going to leave this issue open for now as we iron out the kinks in this feature.

**Comment by frank0434** [comment]
thank you @hol430 

I believe `the number in file path` is a false report. 

instead, the `dot` is probably the issue.
Have the same report says `System. Exception: Unable to find target model` if I use 1) relative path 2) the `lincoln.met` in the path. 

```
.Simulations.New Zealand.Iversen_12.Simulation3.Weather.FileName = .\01raw-data\ClimateAndObserved\lincoln.met
```

**Comment by hol430** [comment]
Ok - looks like apsim isn't properly handling relative paths, hence the problems when you include ./ in your met file name. I will fix this.

**Comment by frank0434** [comment]
Hi Drew. 
Thanks for the effort. 
I tried the latest version of ApsimNG today after Hamish's tip. 

**The feature is working charmingly now.**

I wrote a bit of [documentation](https://frank0434.github.io/2020/03/13/multiply-apsimx-files-via-models-exe/) about how I used it for the lucerne model.

**Comment by hol353** [comment]
@hol430. Good work getting this to work. Can we put the documentation on the Next Gen doco website somewhere?

**Comment by frank0434** [comment]
Hi Drew. 

Introduced the feature to my team members today. 
The _Edit_ will definitely be useful to the modelling team here. 
Team members already have thoughts for applications. 
Thank you for your effort to make our life easier. 

There are some feedbacks from the team that might be helpful. Listed below:   

1. The last bit of the address. The `Copy path to node` function in ApsimxUI provides the address of one level up to the exact node that we want. The last bit needs to be filled in either by knowing the name of the node or using the tooltip in the `Report` module to find out.   

2. It seems not working in the bash environment. The `/Edit` flag seems to be ignored and the `Models.exe` just trigger the simulation straightaway.

3. @rcichota mentioned that he had established a `C#` library to make the address searchable so that we don't have to use the  `Copy path to node` function, instead, just provide a YAML file that has the keywords to specify the address for certain nodes. wondering if it is possible to incorporate it with the current apsimx.

**Comment by hol430** [comment]
Hi Frank, thanks for the feedback:

1. This one seems to be working ok for me. In the screenshot below, if I copy path to node, I get ".Simulations.Simulation.Field" in my clipboard. Is this not what you expect? Or are you seeing different behaviour?

![image](https://user-images.githubusercontent.com/36427516/82512662-129c1b00-9b54-11ea-83fa-f7c71e66a10a.png)

2. I'll test this and get back to you
3. Can you upload one of your .yaml files?

**Comment by frank0434** [comment]
Thanks, Drew. 

1.  Copy the module is working for me charming just like your snapshot. 
it is the litter details after the big node. For example: 
if I want to change the path for the met file and only copy the node like below
`.Simulations.New Zealand.Iversen_12.Simulation3.Weather = C:\Data\Master\01raw-data\ClimateAndObserved\lincoln.met`
Apsimx will return 
`System.Exception: Invalid path: .Simulations.New Zealand.Iversen_12.Simulation3.Weather`
But it will successfully edit the file if I provide the FileName after the copied the node adress. 
.Simulations.New Zealand.Iversen_12.Simulation3.Weather.**FileName** = C:\Data\Master\01raw-data\ClimateAndObserved\lincoln.met

2. It could be the bash environment in my work laptop has been set up correctly. not sure if this could be reproduced in a different machine. 

3. The YAML file is from one of @rcichota's project. I just copied it over. Rogerio is probably the best man to address for this feature. 
[TestYAMLformat.zip](https://github.com/APSIMInitiative/ApsimX/files/4660172/TestYAMLformat.zip)

4. Just recalled that @junqi108 mentioned that if we could indexing the value and only updated the desired ones. For example, only update two values in a 10 layers soil model. I assume that the current `Edit` will overwrite all the existing ones and rewrite the apsimx file with the values in the config file. 
Also, @rcichota said there are some functionality in the apsim classic which can achieve this database-like `updating/appending` functionality.

**Comment by hol430** [comment]
Hi Frank,

1. Yeah, finding the exact name of the property you want to change can be tricky. Currently there is no way to do this from the UI (apart from trial and error with intellisense). There is an old issue created by Hamish (#480) in which he wanted these properties visible in the UI when you click on a component which I implemented but never merged in (there were performance issues). This would sort of do what you want - it would at least save you from having to go through the source code to find property names. I will have a look at this feature and see what it would take to get it merged
2. This seems to be working ok for me. Couple of questions:
- Is apsim returning an exit code of 0 (you can run `echo $?` after running your command to check this)
- What makes you say it's running the simulation?
- Can you post command you're running and your parameter file? The command I'm running is:
`mono Bin/Models.exe Examples/Wheat.apsimx /Edit params.txt`
3. From what I can see, the .yaml file seems to fulfill much the same purpose as the parameter file we're using with the /Edit switch. I imagine that it would suffer from the same problem, that you need to know the name of the parameters you want to change (e.g. StartDate, FileName, etc). I also have concerns about how the components are resolved - e.g. in the example provided, what if you have multiple weather components, or multiple managers called RotationManager (I could see this happening if it was under a factor or replacements, where it's easy to forget about them). 
4. Yes, this should already be possible, you just need to be careful when specifying array indices because apsim reads them as starting at 1. E.g.:

```
.Simulations.Simulation.Field.Soil.Physical.AirDry[1:3] = 0.5,0.4,0.3
```

Result:

![image](https://user-images.githubusercontent.com/36427516/82515346-58a8ad00-9b5b-11ea-9002-9d9ac13f26df.png)

**Comment by frank0434** [comment]
Awesome!!!

For the second one: 

Is apsim returning an exit code of 0 (you can run echo $? after running your command to check this)
```
$ echo $?
1
```
What makes you say it's running the simulation?
_apsim complains it couldn't find certain file rather than saying invalid path and gives lots of the information that usually when a simulation failed to run_
```
$ ../ApsimxLatest/ApsimX/Bin/Models.exe ./test.apsimx /Edit ./config20200312.txt
----------------------------------------------
System.Exception: ERROR in file: .\test.apsimx
Simulation name: Iversen_12SowingDateSD6
Models.Core.ApsimXException: Cannot find weather file 'lincoln.met
```

Can you post command you're running and your parameter file? The command I'm running is:
mono Bin/Models.exe Examples/Wheat.apsimx /Edit params.txt

_I just call `Models.exe` directly without `mono`._
```
$ ../ApsimxLatest/ApsimX/Bin/Models.exe ./test.apsimx /Edit ./config20200312.txt
```
Configuration file is here:
[config20200312.txt](https://github.com/APSIMInitiative/ApsimX/files/4660313/config20200312.txt)

_and if i call mono before apsim, bash will complain it can't find mono command._

**Comment by hol430** [comment]
Hi Frank, that is quite strange, and it does indeed look like it's running the .apsimx file for some reason. Can you upload your .apsimx file?

**Comment by frank0434** [comment]
Here it is: 

[TestApsimxFile.zip](https://github.com/APSIMInitiative/ApsimX/files/4660542/TestApsimxFile.zip)

**Comment by hol430** [comment]
Thanks - I tried editing it with the config file you provided and it seems to be working ok for me. Which version of apsim are you using? If it's a compiled version, how up-to-date is it (ie what is the most recent commit)? You can check in your git gui client, or by running something like `git log -1` from your shell, from inside the ApsimX directory.

I'm also a bit confused why your config file is pointing towards a .met file with a windows-style path if you're running this on linux, although it shouldn't cause any errors until you actually run the file.

**Comment by frank0434** [comment]
It must be an environmental issue. 
I will do a bit more test around it. 
The apsimx I use is a compiled one which has the head commit at 9th April 2020.

```
$ git log -1
commit 964c8576a38290ef688873e2678446526cf3b172 (HEAD -> master, origin/master, origin/HEAD)
Merge: d9d45926d 20dbaca8d
Author: Dean Holzworth <Dean.Holzworth@csiro.au>
Date:   Thu Apr 9 16:50:09 2020 +1000

    Merge pull request #5030 from hol430/bug/Grid

```

I didn't use it in a Linux environment. Should mention this early. 
It is just a bash gui from the git. I was using the git GUI to manage the repo and started to play around the `Edit` flag. 

![image](https://user-images.githubusercontent.com/30789416/82523503-89e7a400-9b80-11ea-8786-a74c99bff8a8.png)

**Comment by hol430** [comment]
Does this work properly if you use a regular command prompt?

**Comment by frank0434** [comment]
Yes, it does. 
I will test it in a real Linux environment.

**Comment by hol430** [comment]
Hi Frank, this is due to the use of msys which will attempt to translate posix-style paths used as arguments to windows-style paths. See [this page](http://mingw.org/wiki/Posix_path_conversion) for more details. Basically you would need to use a second forward slash to escape the other forward slash, like so:

```
models test.apsimx //Edit test.txt
```

**Comment by frank0434** [comment]
Thanks for clarifying this, @hol353.
I run the same command in the Linux environment. It worked fine.

**Comment by frank0434** [comment]
@hol430 

Played a bit more Edit recently. 
Wondering if it is possible to access the user-defined manager script and update values inside the script? 
The manager script values are organised in a key-value pair manner, which is different from the `Models` layout. 
Or do I have to use the `Models` node to update values, like using a `Factor` node to update the `Specification`? 

```
 "$type": "Models.Manager, Models",
                      "Code": "\r\nusing Models.Soils;\r\nusing APSIM.Shared.Utilities;\r\nusing Models.PMF;\r\nusing Models.Core;\r\nusing System;\r\n       ...      ",
                      "Parameters": [
                        {
                          "Key": "CultivarName",
                          "Value": "Lucerne"
                        },
                        {
                          "Key": "InitialRootDepth",
                          "Value": "15"
                        },
                        {
                          "Key": "SowingDate",
                          "Value": "10/21/2010 00:00:00"
                        },
```

Thank you

**Comment by hol430** [comment]
Hi Frank, yes you should be able to edit manager scripts via the /Edit feature, but it doesn't seem to be working, due to a bug. I've fixed the bug in #5278, so when it's merged you should be able to put something like this in your config file:

```
[ManagerName].Script.CultivarName = drew
```

**Comment by frank0434** [comment]
Hi Drew, thanks for getting this fixed so quickly. 
It is working charmingly now. 
But seems still like the old way without the square brackets. 
```
.Simulations.LnP.LandPBase.Field.ManagerFolder.SetCropVariables.Script.MaximumHeight = 390
.Simulations.LnP.LandPBase.Field.ManagerFolder.SlurpSowingRule.Script.SowingDate = 2012-02-17
```

**Comment by frank0434** [comment]
They both working. I made a mistake by mixing the absolute and scope path in the configuration file.

**Comment by hol430** [comment]
Closing this as fixed.

**Comment by frank0434** [comment]
@hol430
wondering if the edit feature seems to be disabled somehow?
I realised this afternoon when verifying some of the simulations and found out there were no changes but simulations were still completed. 

Then update the apsimx to the lastest. still no effect. attached the apsimx file with the configuration file. 
also tried to consult the usage documentation. seems broken? 

Thanks 

------------------error message -------------------------
```
PS C:\Data\ApsimX\ApsimXLatest> git log -n 1                                                                                                                                                                                                                                 commit 4354136b7606b204ae05c980d4ef978f784dedf7 (HEAD -> master, origin/master, origin/HEAD)
Merge: ced9b5d21 a8b4135f6
Author: Drew Holzworth <36427516+hol430@users.noreply.github.com>
Date:   Mon Dec 14 10:03:15 2020 +1000

    Merge pull request #5945 from lie112/WorkingCLEM

    CLEM fixed example graphs to reflect new transaction details
PS C:\Data\ApsimX\ApsimXLatest> C:\Data\ApsimX\ApsimXLatest\Bin\Models.exe [?/]                                                                                                                                                                                              System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at APSIM.Shared.Utilities.DirectoryUtilities.FindFiles(String fileSpec, Boolean recurse) in C:\Data\ApsimX\ApsimXLatest\APSIM.Shared\Utilities\DirectoryUtilities.cs:line 68
   at Models.Program.<>c__DisplayClass5_0.<Run>b__0(String f) in C:\Data\ApsimX\ApsimXLatest\Models\Main.cs:line 60
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Models.Program.Run(Options options) in C:\Data\ApsimX\ApsimXLatest\Models\Main.cs:line 60
PS C:\Data\ApsimX\ApsimXLatest> C:\Data\ApsimX\ApsimXLatest\Bin\Models.exe
System.ArgumentException: No files were specified
   at Models.Program.Run(Options options) in C:\Data\ApsimX\ApsimXLatest\Models\Main.cs:line 63
```
-------------------------------------
[AshleyDene_SD2.zip](https://github.com/APSIMInitiative/ApsimX/files/5687341/AshleyDene_SD2.zip)

**Comment by hol430** [comment]
Hi Frank, thanks for letting me know. Looks like the result of a bad merge - definitely a bug either way. I'll fix the help info while I'm at it. We changed the syntax of the command line interface recently, and while all of the main options are still backwards compatible, it looks that doesn't hold for the help syntax. In the short term you can use `-h` or `--help` to view help info.

**Comment by hol430** [comment]
Just noticed you used `Models.exe [/?]`. I don't think this ever worked, you would need to drop the square brackets. Looks like running `Models.exe /?` is already working to show help info. Will definitely be useful to show help info though if no .apsimx files are specified.

**Comment by frank0434** [comment]
Thanks, Drew.
I was trying various things to see what the outcomes.  🤣 
because I saw the previous builds had 
```
PS C:\Data\ApsimX\ApsimXLatest> .\Bin\Models.exe
Usage: Models ApsimXFileSpec [/Recurse] [/SingleThreaded] [/RunTests] [/Csv] [/Version] [/Verbose] [/Upgrade] [/MultiProcess] [/NumberOfProcessors:xx] [/SimulationNameRegexPattern:xx] [/MergeDBFiles] [/Edit <PathToConfigFile>] [/ListSimulations] [/?]
```

Wondering why apsim stops using `git tag`? 
I saw there are four tags in the `master` branch for the builds 5/6 years ago. 

Thought it might be easier to use `tags` to revert back to any specific builds for certain features. 
I understand that we better use the _Edge_ version because it always has the latest updates, which is good for development since bugs will be addressed immediately. 

sometimes, the `Edge` version might be unsuitable for production work. e.g I'd like to use `Edit` to generate 100K simulations but as soon as I updated the crop models, the software features complain or stop working as I expected.

Not sure if there is a clear line we could separate `software feature` and `module feature`.  
it would be nice to have the infrastructure (`software feature`) tagged whenever there is a major improvement. 

cheers,

**Comment by hol430** [comment]
Yeah, the square brackets in cases like this usually refer to optional arguments, which I think comes from the old backus-naur syntax, although I could be misremembering.

I'm not sure it's a case of us stopping the use of git tags, so much as we never really started using them in the first place...I'm not sure why those few tags exist, possibly they were accidental. I don't really see a problem with adopting the use of tags, although we would end up with a lot of tags, given the frequency with which new releases are generated. I'm also not sure what problem we would be solving by doing so.

I can't think of a way to separate software features and model changes, and often there's some overlap anyway. For collaborative work, your best bet is probably - as you say - to pick a version that seems to work and stick with it.
