### ISSUE TITLE
No FolderName in the report

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5740]
In the wheat.apsimx file, I noticed missing `FolderName` in the table `_Simulations`.

## Case 1
Folder `ChinaFlux` contains three  `Simulation`  (not `Experiment`)

![image](https://user-images.githubusercontent.com/1657381/95928286-509c2300-0e04-11eb-865e-5a13b9f7be06.png)

Empty folder name (i.e. string with zero character) is presented in the table.

![image](https://user-images.githubusercontent.com/1657381/95930041-dd48e000-0e08-11eb-9521-28de55902f3f.png)

## Case 2
In the `Experiment` `TraitMod2015`, the `Simulation` setups sowing cultivar `Hartog`. Consequently, there is an extra simulation `TraitMod2015TOS22-JunCvHartog` which is not defined in the `Factors`. The `FolderName` is `null`.

![image](https://user-images.githubusercontent.com/1657381/95930378-9f988700-0e09-11eb-8083-11492c7efa5a.png)

**Comment by hol430** [comment]
Ah yep definitely a bug. #5742 should fix it, but it's worth noting that the folder name is only written when report data is written. So if you have no report (or if you report on harvesting but the crop is never harvested) then the folder name won't be written. I think.

**Comment by byzheng** [comment]
Thanks for the quick fix. it makes sense to write folder name at report time. How about the extra simulations in case 2?

**Comment by hol430** [comment]
In case 2, the base simulation name shouldn't show up at all unless you run the base simulation in isolation (e.g. by right clicking on it and running it manually). If this happens, #5742 will make the folder name show up as expected.

**Comment by byzheng** [comment]
I clean the data store, then directly run whole wheat.apsimx file. It still show the base simulation name in the _Simulations.

**Comment by hol430** [comment]
Odd, I just tested with the factorial example and the base simulation names aren't showing up (running on latest master branch). I'll double check wheat - are you looking at the TraitMod2015 experiment?

**Comment by byzheng** [comment]
Yes. I believe this is only caused when the base simulation name is not in the factor list.

**Comment by hol430** [comment]
Ah - by base simulation name, I mean the name of the simulation underneath the experiment. In this case, `15TraitModbase`:

![image](https://user-images.githubusercontent.com/36427516/95942262-16437d80-0e26-11eb-9d92-4353474c9f12.png)

This doesn't show up in the _Simulations table for me. However I do see the extra entries which you see - e.g. `TraitMod2015TOS21-MayCvHartog`. These appear to be caused by entries in the observed data. Because there's no folder name in the observed data, there's no corresponding folder name in the _Simulations table. The reason the simulation names in the observed data are saved to _Simulations is because they need a SimulationID for easy merging with predicted data by the PredictedObserved tool.

**Comment by byzheng** [comment]
Get your point. We will have a look at the wheat.apsimx file and fix it.
